### ISSUE TITLE
deployer function need to return error message instead consoling log

### ISSUE THREAD

**Issue by v-shant** [nimbella/nimbella-cli#119]
we are using deployer's (readAndPreapre, build, deploy) in commander. here when I am calling deploy it's doing console log instead of returning in errors.

![image](https://user-images.githubusercontent.com/35557159/119968499-30078e80-bfcb-11eb-88ab-e3b4e30c4451.png)

as in the image, `./build.sh: line 5: virtualenv: command not found` this line needs to be in the response of deployer(in failures array) instead of console.log to let the user know about the error. currently, it's returning `build.sh exited with code 127` which not much useful for the user

**Comment by rabbah** [comment]
Is it possible to capture console.log? For example change it to be a buffer append operation just before calling deployer. This would be a brute force solution if the deployer has no way to pass a logger (which we can fix as well by changing the interface).

**Comment by v-shant** [comment]
there are already some other console logs

`found commands.yaml but no project.yaml found`
`start running ./build.js ...`
`Output of failed ...`
then the actual message

`build.sh : line 5: ....`

if there is a fixed pattern or some string which I can to match and extract the message then I can implement else it might give more confusing statements to user.

**Comment by jthomas** [comment]
@v-shant Can you give me a test project to check this behaviour out?

**Comment by v-shant** [comment]
[deployer test.zip](https://github.com/nimbella/nimbella-cli/files/6649890/deployer.test.zip)


hi @jthomas please use this example

you need to update index.js and update with your own GitHub and namespace values
```
const GITHUB_ACCESS_TOKEN = '<github access token>';
const nsAuth = '<namespace auth>';
const namespace = '<your namesapce>';
```

then run yarn 

and 

node index.js


this will give you something `./build.sh: line 5: virtualenv: command not found` like console log from nimDeployer.buildProject but it doesn't returns any error and moves to deploy - in deploy it fails to deploy the project and gives


[ { Error: './build.sh' exited with code 127
      at ChildProcess.f.on.e (/mnt/d/nimbella/test/node_modules/nimbella-deployer/lib/finder-builder.js:1:18699)
      at ChildProcess.emit (events.js:198:13)
      at maybeClose (internal/child_process.js:982:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Socket.emit (events.js:198:13)
      at Pipe._handle.close (net.js:607:12) context: 'action \'joke\'' } ]

under failures

now, this is not useful information, the useful information was `./build.sh: line 5: virtualenv: command not found` 

so either build or deployer should return the message 




![image](https://user-images.githubusercontent.com/35557159/121928878-3d0fd600-cd5e-11eb-9776-e04e0d967017.png)

this is the output of `nim project deploy github:rabbah/my-command-sets/jokes` same what test code (with nimdeployer) is doing

you can see here as well the error is 

Failures:
 ›   Error: While deploying action 'joke': './build.sh' exited with code 127


but it should be include `./build.sh: line 5: virtualenv: command not found`

**Comment by bhageena** [comment]
In deployer,  `console.log` is used to report progress and `console.warn` to report errors, this behavior can be altered by having custom implementaion of `Feedback` interface by the caller 

Methods `readProject`, `readAndPrepare` and `readPrepareAndBuild`  take `Feedback` parameter,  `deploy` method's only parameter is `DeployStructure`, but it also has `Feedback` as a member property. `Feedback` parameter is an implementation of 

```
 interface Feedback {
    warn(message?: any, ...optionalParams: any[]): void
    progress(message?: any, ...optionalParams: any[]): void
}
```
The default implementation is as below, but in commander we can have a custom implementation to return user friendly messages.
```

class DefaultFeedback implements Feedback {
  warn(message?: any, ...optionalParams: any[]): void {
    console.warn(message, ...optionalParams)
  }

  progress(message?: any, ...optionalParams: any[]): void {
    console.log(message, ...optionalParams)
  }
}
```

**Comment by jthomas** [comment]
@bhageena Can you submit a PR for this?

**Comment by jthomas** [comment]
After discussing with @bhageena - I'm going to close this as Working As Designed due to comment above about how the client can support this. Is that okay @v-shant?
