### ISSUE TITLE
Nim command gives error when creating object on AWS

### ISSUE THREAD

**Issue by Tejusbharadwaj** [nimbella/nimbella-cli#142]
When I try to run `nim object create <filename>`
```
main git:(stats-support-s3-revised) ✗ nim object create test.txt --verbose
  nim:error NotFound: NotFound
  nim:error     at deserializeAws_restXmlHeadObjectCommandError (/Users/tejusbharadwaj/.nvm/versions/node/v14.16.0/lib/node_modules/nimbella-cli/node_modules/@aws-sdk/client-s3/dist/cjs/protocols/Aws_restXml.js:6793:41)
  nim:error     at processTicksAndRejections (internal/process/task_queues.js:93:5)
  nim:error     at async /Users/tejusbharadwaj/.nvm/versions/node/v14.16.0/lib/node_modules/nimbella-cli/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
  nim:error     at async /Users/tejusbharadwaj/.nvm/versions/node/v14.16.0/lib/node_modules/nimbella-cli/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:12:24
  nim:error     at async StandardRetryStrategy.retry (/Users/tejusbharadwaj/.nvm/versions/node/v14.16.0/lib/node_modules/nimbella-cli/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
  nim:error     at async /Users/tejusbharadwaj/.nvm/versions/node/v14.16.0/lib/node_modules/nimbella-cli/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
  nim:error     at async f.getMetadata (/Users/tejusbharadwaj/.nvm/versions/node/v14.16.0/lib/node_modules/nimbella-cli/node_modules/@nimbella/storage/lib/index.js:1:1785)
  nim:error     at async f.exists (/Users/tejusbharadwaj/.nvm/versions/node/v14.16.0/lib/node_modules/nimbella-cli/node_modules/@nimbella/storage/lib/index.js:1:2034)
  nim:error     at async ObjectCreate.uploadFile (/Users/tejusbharadwaj/.nvm/versions/node/v14.16.0/lib/node_modules/nimbella-cli/lib/commands/object/create.js:1:948)
  nim:error     at async ObjectCreate.runCommand (/Users/tejusbharadwaj/.nvm/versions/node/v14.16.0/lib/node_modules/nimbella-cli/lib/commands/object/create.js:1:582) {
  nim:error   '$fault': 'client',
  nim:error   '$metadata': {
  nim:error     httpStatusCode: 404,
  nim:error     requestId: undefined,
  nim:error     extendedRequestId: 'nOefKqCvG5GP4o+JCI32N9aULM0xnxbFmmXpz04UC7/gOJKpuPRdRPKh5bIH5KiAbtjksZ8OKa8=',
  nim:error     cfId: undefined,
  nim:error     attempts: 1,
  nim:error     totalRetryDelay: 0
  nim:error   }
  nim:error } +0ms
 ›   Error: NotFound
```

The same works for GCP.

**Comment by jthomas** [comment]
This should be fixed by https://github.com/nimbella/storage/commit/b72eea3ba3fcfcda0ae88196e698ab14079cf7ff
Will test it now and update all the downstream repos.

**Comment by jthomas** [comment]
I've now published the NPM libraries for the `storage` and `nimbella-deployer` repos. Testing this locally - the bug is fixed. I'll wait for depend-a-bot to open the PR to update the deployer library and then close this when merged. Will get this fix out in the next release of the CLI shortly.
